runtime: python27
api_version: 1
threadsafe: true
instance_class: F1
automatic_scaling:
  max_idle_instances: 1  
  min_pending_latency: automatic  
  max_pending_latency: 30ms
  max_instances: 1

builtins:
- deferred: on
- appstats: off

inbound_services:
- warmup

default_expiration: "5d"

handlers:
- url: /test.*
  login: admin  
  script: gaeunit.application
- url: /favicon.ico
  static_files: app/static/images/favicon.ico
  upload: app/static/images/favicon.ico
- url: /robots.txt
  static_files: app/static/docs/robots.txt
  upload: app/static/docs/robots.txt
- url: /crossdomain.xml
  static_files: app/static/docs/crossdomain.xml
  upload: app/static/docs/crossdomain.xml
- url: /sitemap.xml
  static_files: app/static/docs/sitemap.xml
  upload: app/static/docs/sitemap.xml
- url: /javascripts
  static_dir: app/static/javascripts
- url: /stylesheets
  static_dir: app/static/stylesheets
- url: /images
  static_dir: app/static/images
- url: /docs
  static_dir: app/static/docs
- url: /questions
  static_dir: app/static/questions
- url: /_ereporter
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin
- url: /admin.*
  script: application.app
  login: admin 
- url: /_ah/warmup
  script: application.app
  login: admin 
- url: /.*
  script: application.app
  
